# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wl3BspV2vtyT_JN3iWf4IfrQa7QAKeA
"""

import pandas as pd
baza={
    "FISh": [ "Mukhammadov Azizbek","Aliyev Vali", "Xalilov Durbek", "Azimov Ziyoda", "Azimov Toirjon", "Mukhammadov Dilbek", "Murodjonov Begzod", "Abdullayeva Mohigul", "Qadamova Zuloyho"],
    "Yoshi": [  "20" ,"19", "65","30", "42","22", "19","29","26"],
    "Manzili": [ "Fargona viloyati", "Fargona Shahar","Fargona Shahar","Beshariq MFY","Fargona Shahar", "Toshkent Shahar","Beshariq Mfy","Fargona Shahar","Fargona Shahar"],
    "jinsi": [ "Erkak", "Erkak","Erkak","Ayol","Erkak" ,"Erkak","Erkak","Ayol","Ayol"],
    "Ish joyi":[ "TATUFF","TATUFF","FARDU","FARDU","TATUFF","FARDU","FARDU", "TATUFF", "FARDU" ],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db["jinsi"]=="Erkak"]
print (filtr)

filtr=db[(db["jinsi"]=="Erkak") & (db["Ish joyi"]=="TATUFF")]
print (filtr)